/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppProjectionsRouteImport } from './routes/_app.projections'
import { Route as AppJournalRouteImport } from './routes/_app.journal'
import { Route as AppGoalRouteImport } from './routes/_app.goal'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectionsRoute = AppProjectionsRouteImport.update({
  id: '/projections',
  path: '/projections',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalRoute = AppGoalRouteImport.update({
  id: '/goal',
  path: '/goal',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/calendar': typeof AppCalendarRoute
  '/goal': typeof AppGoalRoute
  '/journal': typeof AppJournalRoute
  '/projections': typeof AppProjectionsRoute
}
export interface FileRoutesByTo {
  '/calendar': typeof AppCalendarRoute
  '/goal': typeof AppGoalRoute
  '/journal': typeof AppJournalRoute
  '/projections': typeof AppProjectionsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/goal': typeof AppGoalRoute
  '/_app/journal': typeof AppJournalRoute
  '/_app/projections': typeof AppProjectionsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calendar' | '/goal' | '/journal' | '/projections'
  fileRoutesByTo: FileRoutesByTo
  to: '/calendar' | '/goal' | '/journal' | '/projections' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/calendar'
    | '/_app/goal'
    | '/_app/journal'
    | '/_app/projections'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projections': {
      id: '/_app/projections'
      path: '/projections'
      fullPath: '/projections'
      preLoaderRoute: typeof AppProjectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journal': {
      id: '/_app/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goal': {
      id: '/_app/goal'
      path: '/goal'
      fullPath: '/goal'
      preLoaderRoute: typeof AppGoalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppGoalRoute: typeof AppGoalRoute
  AppJournalRoute: typeof AppJournalRoute
  AppProjectionsRoute: typeof AppProjectionsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppGoalRoute: AppGoalRoute,
  AppJournalRoute: AppJournalRoute,
  AppProjectionsRoute: AppProjectionsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
